name: superherois
description: "Projeto para saber seu Super Heroi favorito."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.0.10+1
  cupertino_icons: ^1.0.8
  crypto: 3.0.5
  http: ^1.2.2
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  mockito: ^5.4.4


flutter:

  uses-material-design: true

  assets:
    - assets/images/
